using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QuanLiPhongMach
{
    public partial class FrmDSThuoc : Form
    {

        QLPMDataContext db;
        int curRow;
        public FrmDSThuoc()
        {
            InitializeComponent();
        }

        private void Refesh()
        {
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new QuanLiPhongMach.QLPMDataContext().Thuocs;
            ReadOnlyActive();
        }
        private void FrmDSThuoc_Load(object sender, EventArgs e)
        {
            Refesh();
        }

        private void ReadOnlyActive()
        {
            txtTenThuoc.ReadOnly = true;
            txtSoLuong.ReadOnly = true;
            txtDonGia.ReadOnly = true;
            txtDonVi.ReadOnly = true;
        }

        private void barButtonThem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            curRow = 1000;
            txtTenThuoc.Text = "";
            txtSoLuong.Text = "";
            txtDonGia.Text = "";
            txtDonVi.Text = "";

            txtTenThuoc.ReadOnly = false;
            txtSoLuong.ReadOnly = false;
            txtDonVi.ReadOnly = false;
            txtDonGia.ReadOnly = false;
        }

        private void barButtonLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            db = new QLPMDataContext();
            Thuoc th = new Thuoc();

            if (txtTenThuoc.Text != "" && txtSoLuong.Text != "" && txtDonVi.Text != "" && txtDonGia.Text != "")
            {
                if (curRow == 1000)
                {
                    th.TenThuoc = txtTenThuoc.Text;
                    th.SoLuong = int.Parse(txtSoLuong.Text);
                    th.DonGia = int.Parse(txtDonGia.Text);
                    th.DonVi = txtDonVi.Text;

                    db.Thuocs.InsertOnSubmit(th);
                    db.SubmitChanges();
                }
                else
                {
                    th = db.Thuocs.Single(p => p.MaThuoc.ToString() == gridView1.GetRowCellValue(curRow, "MaThuoc").ToString());
                    th.DonGia = int.Parse(txtDonGia.Text);
                    th.SoLuong = int.Parse(txtSoLuong.Text);
                    th.DonVi = txtDonVi.Text;
                    th.TenThuoc = txtTenThuoc.Text;

                    db.SubmitChanges();
                }
            }
            else
            {
                XtraMessageBox.Show("Hãy nhập đầy đủ thông tin!", "Thông báo!", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
            Refesh();
            db = null;
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            curRow = e.FocusedRowHandle;
            db = new QLPMDataContext();
            if (curRow != db.Thuocs.Count())
            {
                ReadOnlyActive();
                txtTenThuoc.Text = gridView1.GetRowCellValue(curRow, "TenThuoc").ToString();
                txtSoLuong.Text = gridView1.GetRowCellValue(curRow, "SoLuong").ToString();
                txtDonGia.Text = gridView1.GetRowCellValue(curRow, "DonGia").ToString();
                txtDonVi.Text = gridView1.GetRowCellValue(curRow, "DonVi").ToString();
            }
            db = null;
        }

        private void barButtonSua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (PhanQuyen.curAcc.ChucVu == "Bác sĩ")
            {
                txtDonGia.ReadOnly = false;
            }
            txtTenThuoc.ReadOnly = false;
            txtSoLuong.ReadOnly = false;
            txtDonVi.ReadOnly = false;
        }

        private void barButtonHuy_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Refesh();
        }

        private void barButtonXoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            db = new QLPMDataContext();
            Thuoc th = new Thuoc();

            if (gridView1.DataRowCount != 0)
            {
                th = db.Thuocs.Single(p => p.MaThuoc.ToString() == gridView1.GetRowCellValue(curRow, "MaThuoc").ToString());

                db.Thuocs.DeleteOnSubmit(th);
                db.SubmitChanges();
            }
            Refesh();
            db = null;
        }
    }
}
