#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiPhongMach
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLPM")]
	public partial class QLPMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBenhNhan(BenhNhan instance);
    partial void UpdateBenhNhan(BenhNhan instance);
    partial void DeleteBenhNhan(BenhNhan instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertChiTietToaThuoc(ChiTietToaThuoc instance);
    partial void UpdateChiTietToaThuoc(ChiTietToaThuoc instance);
    partial void DeleteChiTietToaThuoc(ChiTietToaThuoc instance);
    partial void InsertPhieuKham(PhieuKham instance);
    partial void UpdatePhieuKham(PhieuKham instance);
    partial void DeletePhieuKham(PhieuKham instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    #endregion
		
		public QLPMDataContext() : 
				base(global::QuanLiPhongMach.Properties.Settings.Default.QLPMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLPMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BenhNhan> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietToaThuoc> ChiTietToaThuocs
		{
			get
			{
				return this.GetTable<ChiTietToaThuoc>();
			}
		}
		
		public System.Data.Linq.Table<PhieuKham> PhieuKhams
		{
			get
			{
				return this.GetTable<PhieuKham>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<DoanhThuThang> DoanhThuThangs
		{
			get
			{
				return this.GetTable<DoanhThuThang>();
			}
		}
		
		public System.Data.Linq.Table<BaoCaoThuoc> BaoCaoThuocs
		{
			get
			{
				return this.GetTable<BaoCaoThuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBN;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private EntitySet<PhieuKham> _PhieuKhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBNChanging(int value);
    partial void OnMaBNChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgayKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhamChanged();
    #endregion
		
		public BenhNhan()
		{
			this._PhieuKhams = new EntitySet<PhieuKham>(new Action<PhieuKham>(this.attach_PhieuKhams), new Action<PhieuKham>(this.detach_PhieuKhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					this.OnMaBNChanging(value);
					this.SendPropertyChanging();
					this._MaBN = value;
					this.SendPropertyChanged("MaBN");
					this.OnMaBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_PhieuKham", Storage="_PhieuKhams", ThisKey="MaBN", OtherKey="MaBN")]
		public EntitySet<PhieuKham> PhieuKhams
		{
			get
			{
				return this._PhieuKhams;
			}
			set
			{
				this._PhieuKhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuKhams(PhieuKham entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_PhieuKhams(PhieuKham entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private System.Nullable<System.DateTime> _NgayXuat;
		
		private System.Nullable<int> _TienThuoc;
		
		private System.Nullable<int> _TienKham;
		
		private int _MaPK;
		
		private EntityRef<PhieuKham> _PhieuKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnNgayXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatChanged();
    partial void OnTienThuocChanging(System.Nullable<int> value);
    partial void OnTienThuocChanged();
    partial void OnTienKhamChanging(System.Nullable<int> value);
    partial void OnTienKhamChanged();
    partial void OnMaPKChanging(int value);
    partial void OnMaPKChanged();
    #endregion
		
		public HoaDon()
		{
			this._PhieuKham = default(EntityRef<PhieuKham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuat
		{
			get
			{
				return this._NgayXuat;
			}
			set
			{
				if ((this._NgayXuat != value))
				{
					this.OnNgayXuatChanging(value);
					this.SendPropertyChanging();
					this._NgayXuat = value;
					this.SendPropertyChanged("NgayXuat");
					this.OnNgayXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThuoc", DbType="Int")]
		public System.Nullable<int> TienThuoc
		{
			get
			{
				return this._TienThuoc;
			}
			set
			{
				if ((this._TienThuoc != value))
				{
					this.OnTienThuocChanging(value);
					this.SendPropertyChanging();
					this._TienThuoc = value;
					this.SendPropertyChanged("TienThuoc");
					this.OnTienThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienKham", DbType="Int")]
		public System.Nullable<int> TienKham
		{
			get
			{
				return this._TienKham;
			}
			set
			{
				if ((this._TienKham != value))
				{
					this.OnTienKhamChanging(value);
					this.SendPropertyChanging();
					this._TienKham = value;
					this.SendPropertyChanged("TienKham");
					this.OnTienKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPK", DbType="Int NOT NULL")]
		public int MaPK
		{
			get
			{
				return this._MaPK;
			}
			set
			{
				if ((this._MaPK != value))
				{
					if (this._PhieuKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPKChanging(value);
					this.SendPropertyChanging();
					this._MaPK = value;
					this.SendPropertyChanged("MaPK");
					this.OnMaPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_HoaDon", Storage="_PhieuKham", ThisKey="MaPK", OtherKey="MaPK", IsForeignKey=true)]
		public PhieuKham PhieuKham
		{
			get
			{
				return this._PhieuKham.Entity;
			}
			set
			{
				PhieuKham previousValue = this._PhieuKham.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKham.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._PhieuKham.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaPK = value.MaPK;
					}
					else
					{
						this._MaPK = default(int);
					}
					this.SendPropertyChanged("PhieuKham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaND;
		
		private string _Username;
		
		private string _Password;
		
		private string _ChucVu;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNDChanging(int value);
    partial void OnMaNDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaND", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaND
		{
			get
			{
				return this._MaND;
			}
			set
			{
				if ((this._MaND != value))
				{
					this.OnMaNDChanging(value);
					this.SendPropertyChanging();
					this._MaND = value;
					this.SendPropertyChanged("MaND");
					this.OnMaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietToaThuoc")]
	public partial class ChiTietToaThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private int _MaPK;
		
		private int _MaThuoc;
		
		private System.Nullable<int> _SoLuong;
		
		private string _CachDung;
		
		private EntityRef<PhieuKham> _PhieuKham;
		
		private EntityRef<Thuoc> _Thuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaPKChanging(int value);
    partial void OnMaPKChanged();
    partial void OnMaThuocChanging(int value);
    partial void OnMaThuocChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnCachDungChanging(string value);
    partial void OnCachDungChanged();
    #endregion
		
		public ChiTietToaThuoc()
		{
			this._PhieuKham = default(EntityRef<PhieuKham>);
			this._Thuoc = default(EntityRef<Thuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPK", DbType="Int NOT NULL")]
		public int MaPK
		{
			get
			{
				return this._MaPK;
			}
			set
			{
				if ((this._MaPK != value))
				{
					if (this._PhieuKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPKChanging(value);
					this.SendPropertyChanging();
					this._MaPK = value;
					this.SendPropertyChanged("MaPK");
					this.OnMaPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="Int NOT NULL")]
		public int MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CachDung", DbType="NVarChar(100)")]
		public string CachDung
		{
			get
			{
				return this._CachDung;
			}
			set
			{
				if ((this._CachDung != value))
				{
					this.OnCachDungChanging(value);
					this.SendPropertyChanging();
					this._CachDung = value;
					this.SendPropertyChanged("CachDung");
					this.OnCachDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_ChiTietToaThuoc", Storage="_PhieuKham", ThisKey="MaPK", OtherKey="MaPK", IsForeignKey=true)]
		public PhieuKham PhieuKham
		{
			get
			{
				return this._PhieuKham.Entity;
			}
			set
			{
				PhieuKham previousValue = this._PhieuKham.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKham.Entity = null;
						previousValue.ChiTietToaThuocs.Remove(this);
					}
					this._PhieuKham.Entity = value;
					if ((value != null))
					{
						value.ChiTietToaThuocs.Add(this);
						this._MaPK = value.MaPK;
					}
					else
					{
						this._MaPK = default(int);
					}
					this.SendPropertyChanged("PhieuKham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_ChiTietToaThuoc", Storage="_Thuoc", ThisKey="MaThuoc", OtherKey="MaThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.ChiTietToaThuocs.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.ChiTietToaThuocs.Add(this);
						this._MaThuoc = value.MaThuoc;
					}
					else
					{
						this._MaThuoc = default(int);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuKham")]
	public partial class PhieuKham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPK;
		
		private string _TrieuChung;
		
		private string _Benh;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private System.Nullable<int> _MaBN;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<ChiTietToaThuoc> _ChiTietToaThuocs;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPKChanging(int value);
    partial void OnMaPKChanged();
    partial void OnTrieuChungChanging(string value);
    partial void OnTrieuChungChanged();
    partial void OnBenhChanging(string value);
    partial void OnBenhChanged();
    partial void OnNgayKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhamChanged();
    partial void OnMaBNChanging(System.Nullable<int> value);
    partial void OnMaBNChanged();
    #endregion
		
		public PhieuKham()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._ChiTietToaThuocs = new EntitySet<ChiTietToaThuoc>(new Action<ChiTietToaThuoc>(this.attach_ChiTietToaThuocs), new Action<ChiTietToaThuoc>(this.detach_ChiTietToaThuocs));
			this._BenhNhan = default(EntityRef<BenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPK
		{
			get
			{
				return this._MaPK;
			}
			set
			{
				if ((this._MaPK != value))
				{
					this.OnMaPKChanging(value);
					this.SendPropertyChanging();
					this._MaPK = value;
					this.SendPropertyChanged("MaPK");
					this.OnMaPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrieuChung", DbType="NVarChar(100)")]
		public string TrieuChung
		{
			get
			{
				return this._TrieuChung;
			}
			set
			{
				if ((this._TrieuChung != value))
				{
					this.OnTrieuChungChanging(value);
					this.SendPropertyChanging();
					this._TrieuChung = value;
					this.SendPropertyChanged("TrieuChung");
					this.OnTrieuChungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Benh", DbType="NVarChar(50)")]
		public string Benh
		{
			get
			{
				return this._Benh;
			}
			set
			{
				if ((this._Benh != value))
				{
					this.OnBenhChanging(value);
					this.SendPropertyChanging();
					this._Benh = value;
					this.SendPropertyChanged("Benh");
					this.OnBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="Int")]
		public System.Nullable<int> MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBNChanging(value);
					this.SendPropertyChanging();
					this._MaBN = value;
					this.SendPropertyChanged("MaBN");
					this.OnMaBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_HoaDon", Storage="_HoaDons", ThisKey="MaPK", OtherKey="MaPK")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_ChiTietToaThuoc", Storage="_ChiTietToaThuocs", ThisKey="MaPK", OtherKey="MaPK")]
		public EntitySet<ChiTietToaThuoc> ChiTietToaThuocs
		{
			get
			{
				return this._ChiTietToaThuocs;
			}
			set
			{
				this._ChiTietToaThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_PhieuKham", Storage="_BenhNhan", ThisKey="MaBN", OtherKey="MaBN", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.PhieuKhams.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.PhieuKhams.Add(this);
						this._MaBN = value.MaBN;
					}
					else
					{
						this._MaBN = default(Nullable<int>);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = null;
		}
		
		private void attach_ChiTietToaThuocs(ChiTietToaThuoc entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = this;
		}
		
		private void detach_ChiTietToaThuocs(ChiTietToaThuoc entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThuoc;
		
		private string _TenThuoc;
		
		private string _DonVi;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _DonGia;
		
		private EntitySet<ChiTietToaThuoc> _ChiTietToaThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuocChanging(int value);
    partial void OnMaThuocChanged();
    partial void OnTenThuocChanging(string value);
    partial void OnTenThuocChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public Thuoc()
		{
			this._ChiTietToaThuocs = new EntitySet<ChiTietToaThuoc>(new Action<ChiTietToaThuoc>(this.attach_ChiTietToaThuocs), new Action<ChiTietToaThuoc>(this.detach_ChiTietToaThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50)")]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this.OnTenThuocChanging(value);
					this.SendPropertyChanging();
					this._TenThuoc = value;
					this.SendPropertyChanged("TenThuoc");
					this.OnTenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_ChiTietToaThuoc", Storage="_ChiTietToaThuocs", ThisKey="MaThuoc", OtherKey="MaThuoc")]
		public EntitySet<ChiTietToaThuoc> ChiTietToaThuocs
		{
			get
			{
				return this._ChiTietToaThuocs;
			}
			set
			{
				this._ChiTietToaThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietToaThuocs(ChiTietToaThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_ChiTietToaThuocs(ChiTietToaThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhThuThang")]
	public partial class DoanhThuThang
	{
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private System.Nullable<int> _SoBenhNhan;
		
		private System.Nullable<int> _DoanhThu;
		
		public DoanhThuThang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this._NgayKham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBenhNhan", DbType="Int")]
		public System.Nullable<int> SoBenhNhan
		{
			get
			{
				return this._SoBenhNhan;
			}
			set
			{
				if ((this._SoBenhNhan != value))
				{
					this._SoBenhNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoanhThu", DbType="Int")]
		public System.Nullable<int> DoanhThu
		{
			get
			{
				return this._DoanhThu;
			}
			set
			{
				if ((this._DoanhThu != value))
				{
					this._DoanhThu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaoCaoThuoc")]
	public partial class BaoCaoThuoc
	{
		
		private int _MaThuoc;
		
		private string _TenThuoc;
		
		private string _DonVi;
		
		private System.Nullable<int> _SoLuongSuDung;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<int> _SoLuongConLai;
		
		public BaoCaoThuoc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="Int NOT NULL")]
		public int MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this._MaThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50)")]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this._TenThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this._DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongSuDung", DbType="Int")]
		public System.Nullable<int> SoLuongSuDung
		{
			get
			{
				return this._SoLuongSuDung;
			}
			set
			{
				if ((this._SoLuongSuDung != value))
				{
					this._SoLuongSuDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongConLai", DbType="Int")]
		public System.Nullable<int> SoLuongConLai
		{
			get
			{
				return this._SoLuongConLai;
			}
			set
			{
				if ((this._SoLuongConLai != value))
				{
					this._SoLuongConLai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
